apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespaceDefault }}
  labels:
    name: {{.Release.Name}}
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: {{.Release.Name}}
