apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webinarEPAM
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: webinarEPAM
  chart: 
    spec:
      chart: ./charts/azure-arc-sample
  values:
    replicaCount: 2
