apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-sample
  namespace: default
spec:
  releaseName: default
  chart:
    git: https://github.com/LeonidChetverikov/webinarEPAM.git
    ref: master
    path: charts/azure-arc-sample
  values:
    serviceName: arc-k8s-demo
